{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ferroada.fullname" . }}
  labels:
    {{- include "ferroada.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ferroada.selectorLabels" . | nindent 6 }}
  {{- if hasKey .Values.podDisruptionBudget "minAvailable" }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable | default 1 }}
  {{- end }}
{{- end }}
